package com.example.llmdyn.model;

public enum ErrorCode {
    GEN_LLM_API_ERROR(FailureLevel.LEVEL_1_GENERATION_EXTRACTION),
    GEN_PROVIDER_RESPONSE_INVALID(FailureLevel.LEVEL_1_GENERATION_EXTRACTION),
    GEN_OUTPUT_EMPTY(FailureLevel.LEVEL_1_GENERATION_EXTRACTION),
    GEN_UNKNOWN(FailureLevel.LEVEL_1_GENERATION_EXTRACTION),

    CMP_COMPILATION_FAILED(FailureLevel.LEVEL_2_COMPILATION),
    CMP_CANNOT_FIND_SYMBOL(FailureLevel.LEVEL_2_COMPILATION),
    CMP_PACKAGE_NOT_FOUND(FailureLevel.LEVEL_2_COMPILATION),
    CMP_TYPE_MISMATCH(FailureLevel.LEVEL_2_COMPILATION),
    CMP_SYNTAX_ERROR(FailureLevel.LEVEL_2_COMPILATION),

    CTX_BEAN_CREATION(FailureLevel.LEVEL_3_SPRING_CONTEXT_INIT),
    CTX_UNSATISFIED_DEPENDENCY(FailureLevel.LEVEL_3_SPRING_CONTEXT_INIT),
    CTX_NO_SUCH_BEAN(FailureLevel.LEVEL_3_SPRING_CONTEXT_INIT),
    CTX_CONTEXT_BOOTSTRAP(FailureLevel.LEVEL_3_SPRING_CONTEXT_INIT),

    DB_PERSISTENCE_EXCEPTION(FailureLevel.LEVEL_4_PERSISTENCE_DATABASE),
    DB_DATA_ACCESS_EXCEPTION(FailureLevel.LEVEL_4_PERSISTENCE_DATABASE),
    DB_SQL_EXCEPTION(FailureLevel.LEVEL_4_PERSISTENCE_DATABASE),
    DB_CONSTRAINT_VIOLATION(FailureLevel.LEVEL_4_PERSISTENCE_DATABASE),
    DB_SCHEMA_MISMATCH(FailureLevel.LEVEL_4_PERSISTENCE_DATABASE),

    EXEC_ASSERTION_MISMATCH(FailureLevel.LEVEL_5_FUNCTIONAL_MERGED),
    EXEC_NO_SUCH_METHOD(FailureLevel.LEVEL_5_FUNCTIONAL_MERGED),
    EXEC_CLASS_NOT_FOUND(FailureLevel.LEVEL_5_FUNCTIONAL_MERGED),
    EXEC_INVOCATION_TARGET(FailureLevel.LEVEL_5_FUNCTIONAL_MERGED),
    EXEC_ILLEGAL_ARGUMENT(FailureLevel.LEVEL_5_FUNCTIONAL_MERGED),
    EXEC_UNKNOWN(FailureLevel.LEVEL_5_FUNCTIONAL_MERGED),

    UNCLASSIFIED(FailureLevel.UNCLASSIFIED);

    private final FailureLevel level;

    ErrorCode(FailureLevel level) {
        this.level = level;
    }

    public FailureLevel getLevel() {
        return level;
    }
}

